<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'LINE\\' => array($vendorDir . '/linecorp/line-bot-sdk/src'),
    'KS\\HTTP\\' => array($vendorDir . '/kittinan/php-http/src/KS/HTTP'),
);
